# Generated by Django 4.1.2 on 2022-10-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0002_rename_todo_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='completed',
        ),
    ]
