# Generated by Django 4.1.2 on 2022-10-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0003_rename_complete_task_completed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Todo',
        ),
    ]
